// !This file is generated by `scripts/gen-named-colors.ts`, please do not edit it directly.
/**
 * #000000
 */
export const black = "#000000"

/**
 * #c0c0c0
 */
export const silver = "#c0c0c0"

/**
 * #808080
 */
export const gray = "#808080"

/**
 * #ffffff
 */
export const white = "#ffffff"

/**
 * #800000
 */
export const maroon = "#800000"

/**
 * #ff0000
 */
export const red = "#ff0000"

/**
 * #800080
 */
export const purple = "#800080"

/**
 * #ff00ff
 */
export const fuchsia = "#ff00ff"

/**
 * #008000
 */
export const green = "#008000"

/**
 * #00ff00
 */
export const lime = "#00ff00"

/**
 * #808000
 */
export const olive = "#808000"

/**
 * #ffff00
 */
export const yellow = "#ffff00"

/**
 * #000080
 */
export const navy = "#000080"

/**
 * #0000ff
 */
export const blue = "#0000ff"

/**
 * #008080
 */
export const teal = "#008080"

/**
 * #00ffff
 */
export const aqua = "#00ffff"

/**
 * #ffa500
 */
export const orange = "#ffa500"

/**
 * #f0f8ff
 */
export const aliceblue = "#f0f8ff"

/**
 * #faebd7
 */
export const antiquewhite = "#faebd7"

/**
 * #7fffd4
 */
export const aquamarine = "#7fffd4"

/**
 * #f0ffff
 */
export const azure = "#f0ffff"

/**
 * #f5f5dc
 */
export const beige = "#f5f5dc"

/**
 * #ffe4c4
 */
export const bisque = "#ffe4c4"

/**
 * #ffebcd
 */
export const blanchedalmond = "#ffebcd"

/**
 * #8a2be2
 */
export const blueviolet = "#8a2be2"

/**
 * #a52a2a
 */
export const brown = "#a52a2a"

/**
 * #deb887
 */
export const burlywood = "#deb887"

/**
 * #5f9ea0
 */
export const cadetblue = "#5f9ea0"

/**
 * #7fff00
 */
export const chartreuse = "#7fff00"

/**
 * #d2691e
 */
export const chocolate = "#d2691e"

/**
 * #ff7f50
 */
export const coral = "#ff7f50"

/**
 * #6495ed
 */
export const cornflowerblue = "#6495ed"

/**
 * #fff8dc
 */
export const cornsilk = "#fff8dc"

/**
 * #dc143c
 */
export const crimson = "#dc143c"

/**
 * #00ffff
 */
export const cyan = "#00ffff"

/**
 * #00008b
 */
export const darkblue = "#00008b"

/**
 * #008b8b
 */
export const darkcyan = "#008b8b"

/**
 * #b8860b
 */
export const darkgoldenrod = "#b8860b"

/**
 * #a9a9a9
 */
export const darkgray = "#a9a9a9"

/**
 * #006400
 */
export const darkgreen = "#006400"

/**
 * #a9a9a9
 */
export const darkgrey = "#a9a9a9"

/**
 * #bdb76b
 */
export const darkkhaki = "#bdb76b"

/**
 * #8b008b
 */
export const darkmagenta = "#8b008b"

/**
 * #556b2f
 */
export const darkolivegreen = "#556b2f"

/**
 * #ff8c00
 */
export const darkorange = "#ff8c00"

/**
 * #9932cc
 */
export const darkorchid = "#9932cc"

/**
 * #8b0000
 */
export const darkred = "#8b0000"

/**
 * #e9967a
 */
export const darksalmon = "#e9967a"

/**
 * #8fbc8f
 */
export const darkseagreen = "#8fbc8f"

/**
 * #483d8b
 */
export const darkslateblue = "#483d8b"

/**
 * #2f4f4f
 */
export const darkslategray = "#2f4f4f"

/**
 * #2f4f4f
 */
export const darkslategrey = "#2f4f4f"

/**
 * #00ced1
 */
export const darkturquoise = "#00ced1"

/**
 * #9400d3
 */
export const darkviolet = "#9400d3"

/**
 * #ff1493
 */
export const deeppink = "#ff1493"

/**
 * #00bfff
 */
export const deepskyblue = "#00bfff"

/**
 * #696969
 */
export const dimgray = "#696969"

/**
 * #696969
 */
export const dimgrey = "#696969"

/**
 * #1e90ff
 */
export const dodgerblue = "#1e90ff"

/**
 * #b22222
 */
export const firebrick = "#b22222"

/**
 * #fffaf0
 */
export const floralwhite = "#fffaf0"

/**
 * #228b22
 */
export const forestgreen = "#228b22"

/**
 * #dcdcdc
 */
export const gainsboro = "#dcdcdc"

/**
 * #f8f8ff
 */
export const ghostwhite = "#f8f8ff"

/**
 * #ffd700
 */
export const gold = "#ffd700"

/**
 * #daa520
 */
export const goldenrod = "#daa520"

/**
 * #adff2f
 */
export const greenyellow = "#adff2f"

/**
 * #808080
 */
export const grey = "#808080"

/**
 * #f0fff0
 */
export const honeydew = "#f0fff0"

/**
 * #ff69b4
 */
export const hotpink = "#ff69b4"

/**
 * #cd5c5c
 */
export const indianred = "#cd5c5c"

/**
 * #4b0082
 */
export const indigo = "#4b0082"

/**
 * #fffff0
 */
export const ivory = "#fffff0"

/**
 * #f0e68c
 */
export const khaki = "#f0e68c"

/**
 * #e6e6fa
 */
export const lavender = "#e6e6fa"

/**
 * #fff0f5
 */
export const lavenderblush = "#fff0f5"

/**
 * #7cfc00
 */
export const lawngreen = "#7cfc00"

/**
 * #fffacd
 */
export const lemonchiffon = "#fffacd"

/**
 * #add8e6
 */
export const lightblue = "#add8e6"

/**
 * #f08080
 */
export const lightcoral = "#f08080"

/**
 * #e0ffff
 */
export const lightcyan = "#e0ffff"

/**
 * #fafad2
 */
export const lightgoldenrodyellow = "#fafad2"

/**
 * #d3d3d3
 */
export const lightgray = "#d3d3d3"

/**
 * #90ee90
 */
export const lightgreen = "#90ee90"

/**
 * #d3d3d3
 */
export const lightgrey = "#d3d3d3"

/**
 * #ffb6c1
 */
export const lightpink = "#ffb6c1"

/**
 * #ffa07a
 */
export const lightsalmon = "#ffa07a"

/**
 * #20b2aa
 */
export const lightseagreen = "#20b2aa"

/**
 * #87cefa
 */
export const lightskyblue = "#87cefa"

/**
 * #778899
 */
export const lightslategray = "#778899"

/**
 * #778899
 */
export const lightslategrey = "#778899"

/**
 * #b0c4de
 */
export const lightsteelblue = "#b0c4de"

/**
 * #ffffe0
 */
export const lightyellow = "#ffffe0"

/**
 * #32cd32
 */
export const limegreen = "#32cd32"

/**
 * #faf0e6
 */
export const linen = "#faf0e6"

/**
 * #ff00ff
 */
export const magenta = "#ff00ff"

/**
 * #66cdaa
 */
export const mediumaquamarine = "#66cdaa"

/**
 * #0000cd
 */
export const mediumblue = "#0000cd"

/**
 * #ba55d3
 */
export const mediumorchid = "#ba55d3"

/**
 * #9370db
 */
export const mediumpurple = "#9370db"

/**
 * #3cb371
 */
export const mediumseagreen = "#3cb371"

/**
 * #7b68ee
 */
export const mediumslateblue = "#7b68ee"

/**
 * #00fa9a
 */
export const mediumspringgreen = "#00fa9a"

/**
 * #48d1cc
 */
export const mediumturquoise = "#48d1cc"

/**
 * #c71585
 */
export const mediumvioletred = "#c71585"

/**
 * #191970
 */
export const midnightblue = "#191970"

/**
 * #f5fffa
 */
export const mintcream = "#f5fffa"

/**
 * #ffe4e1
 */
export const mistyrose = "#ffe4e1"

/**
 * #ffe4b5
 */
export const moccasin = "#ffe4b5"

/**
 * #ffdead
 */
export const navajowhite = "#ffdead"

/**
 * #fdf5e6
 */
export const oldlace = "#fdf5e6"

/**
 * #6b8e23
 */
export const olivedrab = "#6b8e23"

/**
 * #ff4500
 */
export const orangered = "#ff4500"

/**
 * #da70d6
 */
export const orchid = "#da70d6"

/**
 * #eee8aa
 */
export const palegoldenrod = "#eee8aa"

/**
 * #98fb98
 */
export const palegreen = "#98fb98"

/**
 * #afeeee
 */
export const paleturquoise = "#afeeee"

/**
 * #db7093
 */
export const palevioletred = "#db7093"

/**
 * #ffefd5
 */
export const papayawhip = "#ffefd5"

/**
 * #ffdab9
 */
export const peachpuff = "#ffdab9"

/**
 * #cd853f
 */
export const peru = "#cd853f"

/**
 * #ffc0cb
 */
export const pink = "#ffc0cb"

/**
 * #dda0dd
 */
export const plum = "#dda0dd"

/**
 * #b0e0e6
 */
export const powderblue = "#b0e0e6"

/**
 * #bc8f8f
 */
export const rosybrown = "#bc8f8f"

/**
 * #4169e1
 */
export const royalblue = "#4169e1"

/**
 * #8b4513
 */
export const saddlebrown = "#8b4513"

/**
 * #fa8072
 */
export const salmon = "#fa8072"

/**
 * #f4a460
 */
export const sandybrown = "#f4a460"

/**
 * #2e8b57
 */
export const seagreen = "#2e8b57"

/**
 * #fff5ee
 */
export const seashell = "#fff5ee"

/**
 * #a0522d
 */
export const sienna = "#a0522d"

/**
 * #87ceeb
 */
export const skyblue = "#87ceeb"

/**
 * #6a5acd
 */
export const slateblue = "#6a5acd"

/**
 * #708090
 */
export const slategray = "#708090"

/**
 * #708090
 */
export const slategrey = "#708090"

/**
 * #fffafa
 */
export const snow = "#fffafa"

/**
 * #00ff7f
 */
export const springgreen = "#00ff7f"

/**
 * #4682b4
 */
export const steelblue = "#4682b4"

/**
 * #d2b48c
 */
export const tan = "#d2b48c"

/**
 * #d8bfd8
 */
export const thistle = "#d8bfd8"

/**
 * #ff6347
 */
export const tomato = "#ff6347"

/**
 * #0000
 */
export const transparent = "#0000"

/**
 * #40e0d0
 */
export const turquoise = "#40e0d0"

/**
 * #ee82ee
 */
export const violet = "#ee82ee"

/**
 * #f5deb3
 */
export const wheat = "#f5deb3"

/**
 * #f5f5f5
 */
export const whitesmoke = "#f5f5f5"

/**
 * #9acd32
 */
export const yellowgreen = "#9acd32"

/**
 * #663399
 */
export const rebeccapurple = "#663399"