import { writeFileSync } from 'fs'
import { Window } from 'happy-dom'

const window = new Window()
const document = window.document

const url = `https://developer.mozilla.org/en-US/docs/Web/CSS/named-color`

const txt = await (await fetch(url)).text()
document.body.innerHTML = txt

const tables = document.querySelectorAll('section table')

const colors: Record<string, string> = {}

tables.forEach((table) => {
  const rows = table.querySelectorAll('tbody tr')

  rows.forEach((row) => {
    const values = row.querySelectorAll('td code').map((n) => n.textContent.trim())
    const keys = values.slice(0, -1)
    const color = values.at(-1)!

    keys.forEach((key) => {
      colors[key] = color
    })
  })
})

delete colors.transparent

writeFileSync(
  'colors/w3c.js',
  [
    '// !This file is generated by `scripts/gen-named-colors.ts`, please do not edit it directly.',
    Object.entries(colors)
      .filter((n) => n[0])
      .map((n) => `export const ${n[0]} = ${JSON.stringify(n[1])}`)
      .join('\n\n'),
  ].join('\n')
)
